---
- name: "Update all packages via apt"
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    autoremove: yes

- name: "Install basic utilities"
  become: yes
  apt:
    name:
      - ansible
      - curl
